# Lab 1: CIFAR10 Challenge

**CIFAR10** (http://www.cs.toronto.edu/~kriz/cifar.html) is one of the most famous ML data sets. 

## Data
* 32x32 color images
* in 10 classes
* 50k training images
* 10k test images



<img src="https://production-media.paperswithcode.com/datasets/CIFAR-10-0000000431-b71f61c0_U5n3Glr.jpg" width=700>

In [42]:
#get data
from keras.datasets import cifar10
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

In [43]:
#traindata: 50k 32X32 rgb images
X_train.shape

(50000, 32, 32, 3)

In [44]:
#labels
y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

## Task: build the best classifier (with feature extration) using the methods you know from ML1+2
* work in small teams (2-4)
* use NumPy pre-processing, feature extraction and hyer-parameter tuning in Scikit-Learn
* no Neural Networks! 
* best test F1-Score after 90min winns! 

In [55]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score

In [56]:
Xnew = np.average(X_train, axis=(1,2))
Xnew

array([[141.20507812, 105.09960938,  64.03710938],
       [130.19921875, 130.36523438, 130.47753906],
       [133.484375  , 135.15234375, 132.58496094],
       ...,
       [ 82.53027344, 109.65039062, 122.93359375],
       [162.17480469, 168.83398438, 177.32128906],
       [138.75292969, 129.59667969, 127.29101562]])

In [59]:
clf = RandomForestClassifier(max_depth=200, random_state=0)
clf.fit(Xnew, y_train)
y_pred = clf.predict(np.average(X_test, axis=(1,2)))
f1_score(y_test, y_pred, average=None)

#bei allen
#array([0.55616032, 0.53646598, 0.34526991, 0.31969027, 0.39822573,
#       0.41167435, 0.51486054, 0.48090371, 0.58903445, 0.51568266])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


array([0.35953979, 0.21610805, 0.14511729, 0.16129032, 0.18042813,
       0.13965607, 0.26396917, 0.17206478, 0.32496577, 0.17831814])